# Template Terraform to deploy to Cloud Infrastructure

# This template allows you to deploy your infrastructure using Terraform to supported cloud providers.
# The workflow allows running tests, security scans on feature branches (as well as master).
# After merging code to master the infrastructure will be deployed to cloud according to the given terraform template.

# Prerequisites: credentials according to used cloud provider.
# For advanced cases, please, follow terraform docs https://www.terraform.io/docs/index.html.


image: hashicorp/terraform

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            services:
              - docker
            script:
              - cd lambda
              - terraform init
              - terraform validate
              - terraform plan
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.4.3
  branches:
    master:
        - step:
            name: Test
            script:
              - cd lambda
              - terraform init
              - terraform validate
              - terraform plan
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.4.3

        - step:
            name: Deploy to Production
            deployment: Production
            trigger: manual
            script:
              - terraform init
              - terraform plan
              - terraform apply -auto-approve


